### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by Cengelsen** [fribyte-code/fribyte.no#1]
We should implement a dark mode for "easier-on-the-eyes"-viewing.

**Comment by timharek** [comment]
Skal dette være basert på OSet og/eller skal vi bruke JavaScript sånn at brukeren kan overskrive og velge selv?

**Comment by Cengelsen** [comment]
Jeg hadde personlig foretrukket javascript som gir brukeren mulighet til å velge selv. :)

**Comment by timharek** [comment]
> Da får de som ikke har blokkert js i nettleseren opp knappen til å velge, mens de som har blokkert js i nettleseren får sin foretrukne modus.

Såvidt jeg vet er ikke det mulig å få begge deler, hvis man skal ha muligheten til å velge mellom lys- og mørkmodus med JS. Men en toggle er implementert i #8 nå, så den er klar for review! 😊 @Cengelsen
