### ISSUE TITLE
Kontakt darkmode bug

### ISSUE THREAD

**Issue by Kremtastic** [fribyte-code/fribyte.no#15]
![Screenshot_1](https://user-images.githubusercontent.com/65462771/190457449-33a1685a-aef6-4650-979f-d21673d53b3d.png)

Names should be white when darkmode is enabled, but appears to be grey/black.
Bug occurred using Edge and Chrome.

**Comment by timharek** [comment]
This does not happen on my machine in Chrome? Have you updated your machine and/or browsers lately? Does this occur on Linux for @Cengelsen ?

**Comment by Cengelsen** [comment]
For me, on Linux Fedora, it ony happens in chrome, but not firefox.

This is chrome:
![darkmode-bug](https://user-images.githubusercontent.com/78857869/190634972-c9b02163-d0cd-4a61-a8fa-511090f039ab.png)

**Comment by timharek** [comment]
Does it only happen on that specific page?

**Comment by timharek** [comment]
Tested on Google Chrome on Windows, bug does not appear... do you guys have any plugins enabled that may produce the bug? @Kremtastic @Cengelsen

**Comment by Cengelsen** [comment]
I opened in private windows with no plugins in chrome and firefox. Bug still appears in chrome, but not in firefox.

**Comment by timharek** [comment]
I suppose someone other than me needs to address the bug, since I cannot reproduce on any of my systems :/

**Comment by timharek** [comment]
Is this bug still present? Can someone with Windows and Google Chrome test?

**Comment by Kremtastic** [comment]
The bug is still present. On Firefox everything works like it is supposed to, but not on Chrome or Edge. I haven't been able to figure out a solution.

**Comment by timharek** [comment]
What about now @Kremtastic?

**Comment by Kremtastic** [comment]
Looks like the bug is gone now! On both chrome and edge.
