### ISSUE TITLE
Public documents

### ISSUE THREAD

**Issue by Cengelsen** [fribyte-code/fribyte.no#2]
We should create page for administrative documents about our organization.
Suggestion for implementation:

A new button in the header, called "Public documents", gives the user the options of "Constitution" (Konstituering), "Resolutions"  (Statutter), "Meeting agendas" (dagsordener), "Activity reports" (Rapport om organisasjonens virksomhet), "Action plan" (Handlingsplaner) and "Meeting reports" (Møtereferater). 

On each subpage, there could be a list of all the documents available. Clicking on the list-items takes the user to the document.

Tasks:

- [x] new button in the navbar, called "Public documents"
- [x] subpage of "Public documents": "Constitution"
- [x] subpage of "Public documents": "Resolutions"
- [x] subpage of "Public documents": "Meeting agendas"
- [x] subpage of "Public documents": "Activity reports"
- [x] subpage of "Public documents": "Meeting reports"
- [x] list of relevant documents on each subpage
- [x] clicking on the list-item takes you to the document

**Comment by timharek** [comment]
Denne issuen blir muligens mer oversiktlig hvis den blir redigert til å inkludere en punktliste med forslagene, fremfor en setning 💭 

Og gvorfor er denne issuen på engelsk? Er det noe vi skal fortsette med? 😇 @Cengelsen
