### ISSUE TITLE
Add big thing on frontpage for Bergen Open Source Konferanse

### ISSUE THREAD

**Issue by Celsiusss** [fribyte-code/fribyte.no#47]
Add a big thing promoting our conferance on the frontpage of fribyte.no. Should be a button redirecting boskonf.no

**Comment by mathiash98** [comment]
Here is the big thing 
![image](https://github.com/fribyte-code/fribyte.no/assets/5204006/fe79a12e-9ff1-4a6c-9f03-d688aff26aa7)
