### ISSUE TITLE
:bento: Add "Velferdstinget Vest"-logo

### ISSUE THREAD

**Issue by SindreKjelsrud** [fribyte-code/fribyte.no#83]
Required by them as we've been getting some funds from them. Placement should be somewhere on the website, maybe footer? :sweat_smile:

**Comment by nheek** [comment]
Do they really require it? If yes, will you send the document that says so so I can see the requirement or something? Thanksss

**Comment by SindreKjelsrud** [comment]
> Do they really require it? If yes, will you send the document that says so so I can see the requirement or something? Thanksss

@nheek Yes, check the general-channel on Mattermost. Daniel sent the document there on the 11th of April :sweat_smile:

**Comment by nheek** [comment]
Aha, so there's really no requirement as long as they're mentioned. Got it!
